# SPDX-FileCopyrightText: 2026 Comptoir des Signaux / Pascal Chevallot
# SPDX-License-Identifier: EUPL-1.2
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Réécrit les métadonnées d'un fichier OOXML (.docx, .pptx, .xlsx) avec des
valeurs humaines, en effaçant les traces de génération automatique
(creator « python-docx »/« python-pptx », description « generated by ... »,
dates factices 2013, Application « Macintosh », Manager/Company vides).

Engine-agnostique : opère directement sur le zip après sauvegarde, sans repasser
par python-docx / python-pptx / openpyxl (qui réécriraient app.xml). Les trois
formats partagent la structure docProps/core.xml + docProps/app.xml, donc le même
helper sert pour Word, PowerPoint et Excel.

Règle CdS (ligne rouge) : aucun livrable ne sort avec des métadonnées de
génération automatique. Voir SKILL.md, section « Métadonnées humaines ».

Usage :
    from set_ooxml_metadata import apply_metadata
    apply_metadata("livrable.docx", {
        "title": "...", "subject": "...",
        "author": "Pascal Chevallot; Comptoir des Signaux",
        "keywords": "...", "comments": "...", "category": "...",
        "last_modified_by": "Pascal Chevallot",
        "manager": "Pascal Chevallot",
        "company": "Comptoir des Signaux",
        "created": "2026-06-24T09:00:00Z",
        "modified": "2026-06-28T11:00:00Z",
        # "application": "Microsoft Office Word",  # défaut ; adapter PowerPoint/Excel
    })

PDF (hors OOXML) : poser Author/Title/Subject/Keywords et nettoyer Producer/Creator
avec exiftool ou pikepdf ; ne jamais laisser le nom d'une bibliothèque.
"""
import re, os, time, zipfile
from xml.sax.saxutils import escape

CORE_TMPL = (
    "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>\n"
    '<cp:coreProperties '
    'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
    'xmlns:dc="http://purl.org/dc/elements/1.1/" '
    'xmlns:dcterms="http://purl.org/dc/terms/" '
    'xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    "<dc:title>{title}</dc:title>"
    "<dc:subject>{subject}</dc:subject>"
    "<dc:creator>{author}</dc:creator>"
    "<cp:keywords>{keywords}</cp:keywords>"
    "<dc:description>{comments}</dc:description>"
    "<cp:lastModifiedBy>{last_modified_by}</cp:lastModifiedBy>"
    "<cp:revision>{revision}</cp:revision>"
    '<dcterms:created xsi:type="dcterms:W3CDTF">{created}</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">{modified}</dcterms:modified>'
    "<cp:category>{category}</cp:category>"
    "</cp:coreProperties>"
)

DEFAULTS = {
    "title": "", "subject": "", "author": "", "keywords": "", "comments": "",
    "last_modified_by": "", "revision": "1", "created": "", "modified": "",
    "category": "", "application": "Microsoft Office Word", "manager": "",
    "company": "",
}


def _insert_app_tag(xml, tag, value):
    """Insère <tag> à une position conforme au schéma des propriétés étendues.

    L'ordre compte : Word, Excel et PowerPoint signalent un contenu illisible si
    Manager ou Company sont ajoutés après AppVersion. Les fichiers Office réels
    les placent juste après TitlesOfParts (ou, à défaut, avant AppVersion).
    """
    frag = f"<{tag}>{value}</{tag}>"
    for ancre in ("</TitlesOfParts>", "</HeadingPairs>", "</ScaleCrop>",
                  "</DocSecurity>"):
        if ancre in xml:
            return xml.replace(ancre, ancre + frag, 1)
    m = re.search(r"<AppVersion>", xml)
    if m:
        return xml[:m.start()] + frag + xml[m.start():]
    return xml.replace("</Properties>", frag + "</Properties>")


def _normaliser_properties(xml):
    """Déplie un <Properties .../> auto-fermant en <Properties ...></Properties>.

    docx-js écrit un app.xml réduit à un élément vide auto-fermant. Sans
    </Properties>, aucune insertion n'avait de point d'ancrage : le helper
    repartait sans rien écrire, et le livrable sortait sans Application, sans
    gestionnaire ni société, en silence (constaté le 11/09/2026 sur quatre
    documents produits par docx-js)."""
    return re.sub(r"(<Properties\b[^>]*?)\s*/>", r"\1></Properties>", xml, count=1)


def _properties_vide(xml):
    """Vrai si le corps de <Properties> ne contient aucun élément."""
    m = re.search(r"<Properties\b[^>]*>(.*?)</Properties>", xml, re.S)
    return m is not None and not re.search(r"<\w", m.group(1))


def _patch_app(xml, application, manager, company):
    """Met à jour Application, Manager, Company dans app.xml.

    Application est remplacé sur place (sa position d'origine est correcte).
    Manager et Company sont retirés puis réinsérés à une position conforme :
    un fichier produit par une version antérieure de ce helper peut les porter
    après AppVersion, ce qui déclenche un message d'erreur à l'ouverture.
    """
    xml = _normaliser_properties(xml)
    if _properties_vide(xml):
        # Properties vide : on écrit la séquence dans l'ordre du schéma, où
        # Manager et Company précèdent Application, et AppVersion ferme.
        bloc = (f"<Manager>{escape(manager)}</Manager>"
                f"<Company>{escape(company)}</Company>"
                f"<Application>{escape(application)}</Application>"
                f"<AppVersion>16.0000</AppVersion>")
        return xml.replace("</Properties>", bloc + "</Properties>", 1)

    v = escape(application)
    new, n = re.subn(r"<Application/>", f"<Application>{v}</Application>", xml)
    if n == 0:
        new, n = re.subn(r"<Application>.*?</Application>",
                         f"<Application>{v}</Application>", xml, flags=re.S)
    xml = new if n else _insert_app_tag(xml, "Application", v)

    for tag, val in (("Manager", manager), ("Company", company)):
        xml = re.sub(rf"<{tag}/>", "", xml)
        xml = re.sub(rf"<{tag}>.*?</{tag}>", "", xml, flags=re.S)
        xml = _insert_app_tag(xml, tag, escape(val))
    return xml


def _w3cdtf(valeur=None):
    """Retourne une date W3CDTF valide. Jamais de chaîne vide.

    Une date `dcterms:W3CDTF` vide rend le fichier invalide : Word et Excel
    affichent « problème avec le contenu » à l'ouverture, puis récupèrent en
    ignorant la propriété. C'est la cause n° 1 des messages d'erreur sur les
    livrables générés (constaté le 29/07/2026 sur un DOCX et un XLSX).
    """
    if valeur:
        return str(valeur)
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def apply_metadata(path, meta):
    """Réécrit core.xml et app.xml du fichier OOXML `path` avec le dict `meta`."""
    m = dict(DEFAULTS)
    m.update(meta)
    m["created"] = _w3cdtf(m.get("created"))
    m["modified"] = _w3cdtf(m.get("modified"))
    core = CORE_TMPL.format(**{k: escape(str(m[k])) for k in DEFAULTS})
    tmp = f"{path}.metatmp"
    with zipfile.ZipFile(path) as zin, \
         zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "docProps/core.xml":
                data = core.encode("utf-8")
            elif item.filename == "docProps/app.xml":
                data = _patch_app(data.decode("utf-8"), m["application"],
                                  m["manager"], m["company"]).encode("utf-8")
            zout.writestr(item, data)
    os.replace(tmp, path)
    return path
